//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Liberary_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public book()
        {
            this.Processes = new HashSet<Process>();
        }
    
        public int book_id { get; set; }
        public string title { get; set; }
        public int author_Id { get; set; }
        public string name { get; set; }
        public string publisher { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime joinDate { get; set; }
        public System.DateTime publishDate { get; set; }
        public int copiesCount { get; set; }
        public int availableCopies { get; set; }
        public int shelfNumber { get; set; }
        public int NoOfPages { get; set; }
        public int cat_id { get; set; }
        public string ISBN { get; set; }
        public byte[] cover { get; set; }
    
        public virtual author author { get; set; }
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process> Processes { get; set; }
    }
}
