//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Liberary_System
{
    using System;
    
    public enum read_borrow : int
    {
        Read = 0,
        Borrow = 1
    }
}
