//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Liberary_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.Processes = new HashSet<Process>();
        }
    
        public int user_id { get; set; }
        public string fName { get; set; }
        public string lName { get; set; }
        public Nullable<role> role { get; set; }
        public System.DateTime birthDate { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public bool isDeleted { get; set; }
        public bool firstLogin { get; set; }
        public string email { get; set; }
        public int password { get; set; }
        public bool is_Blocked { get; set; }
        public byte[] image { get; set; }
    
        public virtual employee employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Process> Processes { get; set; }
    }
}
